---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metricsbin
  labels:
    app.kubernetes.io/name: metricsbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: metricsbin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: metricsbin
    spec:
      containers:
      - name: metricsbin
        image: quay.io/coryodaniel/metricsbin:v0.0.1
        ports:
        - name: web
          containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: metricsbin
  labels:
    app.kubernetes.io/name: metricsbin
spec:
  selector:
    app.kubernetes.io/name: metricsbin
  ports:
  - name: web
    port: 8080
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metricsbin
  labels:
    app.kubernetes.io/name: metricsbin
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: metricsbin
  endpoints:
  - port: web